api:
  prefix:
jwt:
  expiration: 86400
  secretKey:
server:
  port: 5000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 'null'
    url: jdbc:mysql://localhost:3306/<DB_name>?useSSL=false&serverTimezone=UTC
    username:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      hibernate: 'null'
    show-sql: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
